---
title: "Examine features before CHTC"
author: "Claire Punturieri"
date: "`r lubridate::today()`"
format: 
  html: 
    embed-resources: true
    toc: true 
    toc_depth: 4
editor_options: 
  chunk_output_type: console
---

## Set up

```{r}
#| include: false

library(tidyverse) 
options(conflicts.policy = "depends.ok")


source("~/github/proj_risk/shared/fun_chtc.R")
source("_chtc/training_controls_gps.R")  
source("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true")

path_chtc <- format_path("risk/data_processed/chtc")
path_gps <- format_path("risk/data_processed/gps")
```

```{r}
 d <- read_csv(fn, show_col_types = FALSE)
d <- format_data(d)
splits <- d %>% 
  make_splits(cv_resample_type, cv_resample, cv_outer_resample, 
              cv_inner_resample, cv_group, cv_strat = cv_strat,
              the_seed = seed_splits)

config <- configs %>%
    filter(config_num == config_current)
  rec <- build_recipe(d = d, config = config)
  
  rec_prep <- rec |> 
  prep(training = d)
  
  feat_trn <- rec_prep |> 
  bake(new_data = NULL)
  
  feat_trn |> names()
```