---
title: "EDA of CHTC features"
author: "Claire Punturieri"
date: "`r lubridate::today()`"
format: 
  html:
    toc: true
    toc_depth: 4
    embed-resources: true
editor_options: 
  chunk_output_type: console
params:
  window: "day"
  roll_dur: 1 # 1 24
  version: "v4" # go back and remove this
  sample: "gps" # ema messages
---

# Housekeeping

## Code Status


## Notes


# Set up

## Set up environment

```{r}
#| message: false
#| warning: false

options(conflicts.policy = "depends.ok")
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true", 
                      sha1 = "a58e57da996d1b70bb9a5b58241325d6fd78890f")
library(tidyverse)
```

## Paths

```{r}
name_job <- str_c("features_", params$sample, "_", params$window, "_", params$roll_dur, "h_", params$version)

path_chtc <- format_path(str_c("studydata/risk/chtc/gps/", name_job, "/output"))
path_shared <- format_path("studydata/risk/data_processed/shared")
```

## Packages and source

```{r}
#| message: false
#| warning: false
#| echo: false

# for data wrangling
library(tidyverse)
library(lubridate)

# helpful lab functions
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/fun_eda.R?raw=true",
 sha1 = "c045eee2655a18dc85e715b78182f176327358a7"
)

# adjust plot visuals
theme_set(theme_classic())
options(tibble.width = Inf, dplyr.print_max = Inf)
```

## Load in data

```{r}
features <- read_csv(here::here(path_chtc, "features_chtc.csv"), 
                 show_col_types = FALSE)
```

## EDA

Verify percentage of lapses looks reasonable.
```{r}
features |> 
  janitor::tabyl(lapse)
```

Overview across all categories.
```{r}
features |>  
  skimr::skim_without_charts() |> 
  select(skim_variable, n_missing, complete_rate, numeric.p0, numeric.p50, 
         numeric.p100) |>
  filter(!skim_variable == "subid" & !skim_variable == "label_num") |> 
  arrange(desc(numeric.p100), skim_variable) 
```

Check raw scores (numeric.p0 should = 0).
```{r}
features |>  
  skimr::skim_without_charts() |> 
  select(skim_variable, n_missing, complete_rate, numeric.p0, numeric.p50, 
         numeric.p100) |>
  filter(!skim_variable == "subid" & !skim_variable == "label_num") |>
  filter(grepl("rrate|rvar", skim_variable)) |> 
  arrange(desc(numeric.p0), skim_variable)
```

Check difference scores (numeric.p0 can be less than 0)
```{r}
features |>  
  skimr::skim_without_charts() |> 
  select(skim_variable, n_missing, complete_rate, numeric.p0, numeric.p50, 
         numeric.p100) |>
  filter(!skim_variable == "subid" & !skim_variable == "label_num") |>
  filter(grepl("drate|dvar", skim_variable)) |> 
  arrange(desc(numeric.p0), skim_variable)
```

Location variance scores, sorted by missingness.
```{r}
features |>  
  skimr::skim_without_charts() |> 
  select(skim_variable, n_missing, complete_rate, numeric.p0, numeric.p50, 
         numeric.p100) |>
  filter(!skim_variable == "subid" & !skim_variable == "label_num") |>
  filter(grepl("rvar|dvar", skim_variable)) |> 
  arrange(desc(n_missing), skim_variable)
```

### Save out to shared folder
```{r}
features |>
  write_csv(here::here(path_shared, str_c("features_", params$sample, "_",
                                       params$window, "_",
                                       params$roll_dur, "h.csv")))
```