---
title: "EDA of CHTC features"
author: "Claire Punturieri"
date: "`r lubridate::today()`"
format: 
  html:
    toc: true
    toc_depth: 4
    embed-resources: true
editor_options: 
  chunk_output_type: console
params:
  window: "day"
  roll_dur: 1 # 1 24
  sample: "gps" # ema messages
---

## Set up environment

```{r}
#| message: false
#| warning: false

options(conflicts.policy = "depends.ok")
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true", 
                      sha1 = "de12d764438078a9341db9bc0b2472c87e0ae846")
library(tidyverse)
```

## Paths

```{r}
name_job <- str_c("features_", params$sample, "_", params$window, "_", params$roll_dur, "h")

path_chtc <- format_path(str_c("studydata/risk/chtc/gps/", name_job, "/output"))
path_shared <- format_path("studydata/risk/data_processed/shared")
```

## Packages and source

```{r}
#| message: false
#| warning: false
#| echo: false

# for data wrangling
library(tidyverse)
library(lubridate)

# helpful lab functions
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/fun_eda.R?raw=true",
 sha1 = "c045eee2655a18dc85e715b78182f176327358a7"
)

# adjust plot visuals
theme_set(theme_classic())
options(tibble.width = Inf, dplyr.print_max = Inf)
```

## Load in data

```{r}
features <- read_csv(here::here(path_chtc, "features_chtc.csv"), 
                 show_col_types = FALSE)
```

## Correlations

### Alcohol
```{r}
cor_table <- data.frame(
  period = c("6h", "12h", "24h", "48h", "72h", "168h"),
  correlation = c(
    cor(features$p6.l0.rratesum_duration.alcohol.yes, features$p6.l0.rratesum_duration.alcohol.no),
    cor(features$p12.l0.rratesum_duration.alcohol.yes, features$p12.l0.rratesum_duration.alcohol.no),
    cor(features$p24.l0.rratesum_duration.alcohol.yes, features$p24.l0.rratesum_duration.alcohol.no),
    cor(features$p48.l0.rratesum_duration.alcohol.yes, features$p48.l0.rratesum_duration.alcohol.no),
    cor(features$p72.l0.rratesum_duration.alcohol.yes, features$p72.l0.rratesum_duration.alcohol.no),
    cor(features$p168.l0.rratesum_duration.alcohol.yes, features$p168.l0.rratesum_duration.alcohol.no)
  )
)

cat("Correlation between RAW 'alcohol.yes' and 'alcohol.no' rates\n\n")
print(cor_table)
```

```{r}
cor_table <- data.frame(
  period = c("6h", "12h", "24h", "48h", "72h", "168h"),
  correlation = c(
    cor(features$p6.l0.dratesum_duration.alcohol.yes, features$p6.l0.dratesum_duration.alcohol.no),
    cor(features$p12.l0.dratesum_duration.alcohol.yes, features$p12.l0.dratesum_duration.alcohol.no),
    cor(features$p24.l0.dratesum_duration.alcohol.yes, features$p24.l0.dratesum_duration.alcohol.no),
    cor(features$p48.l0.dratesum_duration.alcohol.yes, features$p48.l0.dratesum_duration.alcohol.no),
    cor(features$p72.l0.dratesum_duration.alcohol.yes, features$p72.l0.dratesum_duration.alcohol.no),
    cor(features$p168.l0.dratesum_duration.alcohol.yes, features$p168.l0.dratesum_duration.alcohol.no)
  )
)

cat("Correlation between DIFFERENCE 'alcohol.yes' and 'alcohol.no' rates\n\n")
print(cor_table)
```

### Drank
```{r}
cor_table <- data.frame(
  period = c("6h", "12h", "24h", "48h", "72h", "168h"),
  correlation = c(
    cor(features$p6.l0.rratesum_duration.drank.yes, features$p6.l0.rratesum_duration.drank.no),
    cor(features$p12.l0.rratesum_duration.drank.yes, features$p12.l0.rratesum_duration.drank.no),
    cor(features$p24.l0.rratesum_duration.drank.yes, features$p24.l0.rratesum_duration.drank.no),
    cor(features$p48.l0.rratesum_duration.drank.yes, features$p48.l0.rratesum_duration.drank.no),
    cor(features$p72.l0.rratesum_duration.drank.yes, features$p72.l0.rratesum_duration.drank.no),
    cor(features$p168.l0.rratesum_duration.drank.yes, features$p168.l0.rratesum_duration.drank.no)
  )
)

cat("Correlation between RAW 'drank.yes' and 'drank.no' rates\n\n")
print(cor_table)
```

```{r}
cor_table <- data.frame(
  period = c("6h", "12h", "24h", "48h", "72h", "168h"),
  correlation = c(
    cor(features$p6.l0.dratesum_duration.drank.yes, features$p6.l0.dratesum_duration.drank.no),
    cor(features$p12.l0.dratesum_duration.drank.yes, features$p12.l0.dratesum_duration.drank.no),
    cor(features$p24.l0.dratesum_duration.drank.yes, features$p24.l0.dratesum_duration.drank.no),
    cor(features$p48.l0.dratesum_duration.drank.yes, features$p48.l0.dratesum_duration.drank.no),
    cor(features$p72.l0.dratesum_duration.drank.yes, features$p72.l0.dratesum_duration.drank.no),
    cor(features$p168.l0.dratesum_duration.drank.yes, features$p168.l0.dratesum_duration.drank.no)
  )
)

cat("Correlation between DIFFERENCE 'drank.yes' and 'drank.no' rates\n\n")
print(cor_table)
```

### Avoid
```{r}
cor_table <- data.frame(
  period = c("6h", "12h", "24h", "48h", "72h", "168h"),
  correlation = c(
    cor(features$p6.l0.rratesum_duration.avoid.yes, features$p6.l0.rratesum_duration.avoid.no),
    cor(features$p12.l0.rratesum_duration.avoid.yes, features$p12.l0.rratesum_duration.avoid.no),
    cor(features$p24.l0.rratesum_duration.avoid.yes, features$p24.l0.rratesum_duration.avoid.no),
    cor(features$p48.l0.rratesum_duration.avoid.yes, features$p48.l0.rratesum_duration.avoid.no),
    cor(features$p72.l0.rratesum_duration.avoid.yes, features$p72.l0.rratesum_duration.avoid.no),
    cor(features$p168.l0.rratesum_duration.avoid.yes, features$p168.l0.rratesum_duration.avoid.no)
  )
)

cat("Correlation between RAW 'avoid.yes' and 'avoid.no' rates\n\n")
print(cor_table)
```

```{r}
cor_table <- data.frame(
  period = c("6h", "12h", "24h", "48h", "72h", "168h"),
  correlation = c(
    cor(features$p6.l0.dratesum_duration.avoid.yes, features$p6.l0.dratesum_duration.avoid.no),
    cor(features$p12.l0.dratesum_duration.avoid.yes, features$p12.l0.dratesum_duration.avoid.no),
    cor(features$p24.l0.dratesum_duration.avoid.yes, features$p24.l0.dratesum_duration.avoid.no),
    cor(features$p48.l0.dratesum_duration.avoid.yes, features$p48.l0.dratesum_duration.avoid.no),
    cor(features$p72.l0.dratesum_duration.avoid.yes, features$p72.l0.dratesum_duration.avoid.no),
    cor(features$p168.l0.dratesum_duration.avoid.yes, features$p168.l0.dratesum_duration.avoid.no)
  )
)

cat("Correlation between DIFFERENCE 'avoid.yes' and 'avoid.no' rates\n\n")
print(cor_table)
```