---
title: "Study GPS Notes"
author: "Claire Punturieri"
editor: visual
---

# Housekeeping

## Notes

Last updated 7/14/2025.

Note that there will be some overlap between model and feature versions.

## To do/next steps

-   Create beta calibration reprex

-   Finish circadian movement feature engineering

# File storage

This section details where different data are stored relating to the GPS study.

# Feature engineering

7/1/2025

-   Generated spectra for each subject while on study. Saved in risk/data_processed/gps. Need to check to make sure these are set to the same scale.

-   Might need to consider interpolating GPS data. Pulled some information and put it in the mak_circadian file.

-   Before interpolating, will check out k-means approach to identifying location clusters. That might clean up the data enough.

Week of 6/23/2025

-   Need to figure out what threshold of missing data to tolerate when doing CM calculations. lsp() function only needs 3 data points but we definitely need more than that to accurately calculate spectra. Currently have the threshold set to 42 (which would be about a sample every 4 hours). Biological rhythms research is sparse on this, but the conclusion seems to be "the more the better"!

-   Aligned data to start for all subjects at midnight on day two of participation so rhythms are aligned.

6/18/2025

-   Created a new file which combines gps features, weather features, and the stratification file to create a combine features file. This file is in data_processed/gps. Eventually will need to add in circadian movement.

-   Worked more on processing circadian movement. Turns out there's only about 3% of missing data, and there are certain subjects who have more missing data than others. Next step is to explore interpolation options or potentially nixing some subjects.

6/17/2025

-   Was concerned about some very cold weather variables (avgt of -18!) so manually queried using RCC-ACIS. Looks like these values are correct and it was just a cold January in 2019.

-   Circadian movement processing needs closer inspection. Need to first assess how much missing data there is and then figure out an imputation strategy.

6/11/2025

-   After rerunning GPS features on 6/10 (v6), noticed that community space / recreation, public drinking space, temporary residence, and travel stop all have 0s for p0 p50 p100 – I suspect this has to do with spacing in variable names. I checked and this was also the case with the previous version of features, so I'm also guessing this hasn't been caught before. Confirmed has to do with spacing.

-   V7 GPS features were checked and saved out. Now there are no features that are all 0s!

-   Weather features were generated (generated very fast so ask John about how to string batches together better so CHTC doesn't get mad at me). The features look fine, but there are some very low temps (checked in the weather raw file and confirmed those exist so it's not a calculation error). Note to manually check the weather for some of those days as a sanity check.

Past 1hr roll feature versions:

-   V6:

-   V5:

-   V4:

-   V3:

-   V2:

-   V1:

-   For 24hr roll feature documentation, see GitHub.

# Modeling

7/22/2025

-   Had the thought that maybe cal_estimate_beta() is modifying the inputs to beta_calibration() in some way prior to passing it into the function and perhaps that is why I am having difficulty replicating. Did some sleuthing and looks like this is the case. cal_estimate_beta() changes the outcome variable from a factor to numeric prior to passing it in to beta_calibration(). Adding that in to my code enables me to reproduce the error.

-   Finalized and published beta calibration reprex.

7/21/2025

-   While working on beta calibration reprex, noticed that I can't replicate the same error I get in mak_local_preds. Not sure why this is. Started comparing all of the objects in my environment, they all look the same so unsure what the issue could be.

Week of 7/14/2025

-   Note to self that changed stationary training_controls file for V9 to match updated recipe. I don't think this should impact anything because the main changes were removing label_num and changing strat_cv to just strat.

<!-- -->

-   Started working in mak_local_preds and ana_probs to calibrate model. Model seems very uncalibrated! Note that beta calibration fails.

-   Chatted with John, established that a reprex needs to be made to understand what is causing beta calibration to fail. Started outlining reprex.

7/3/2025

-   GLMnet model may be fine, need to evaluate features.

-   Next steps will be to pull from scripts Madison and John wrote to evaluate xgboost model performance.

7/2/2025

-   GLMnet performance considerably worse (.659). Looks like there might be some issues with HP2? Ask John.

7/1/2025

-   Started running GLMnet

Week of 6/23/2025

-   auROC of model including weather features was not markedly improved (.742, about the same as improvements gained from adding stratification). Next steps will be to explore feature importance to assess utility of feature. First step is to run GLMnet and second step is to check calibration of XGBoost and look at SHAP values.

\
6/18/2025

-   V9 model started, which includes hour roll features for GPS and weather and the stratification variable (low/high lapse counts).

-   Training controls file was updated in meeting with JC to 1) work across different model types; and 2) to anticipate taking in a features file which already includes the stratification variable.

Model history prior to V9:

-   V8: same V6/V7 features but testing out different forms of stratification

-   V7: Claire thought she made filtering changes but she accidentally didn't, so is functionally the same as V6 :\^) Oops!

-   V6: same model as V5 but updated features to roll by hour instead of by 24 hours

-   V5: recalculate preliminary context features (location variance, time in transit, time spent out of the house in the evening)

-   V4: add in preliminary context features (location variance, time in transit, time spent out of the house in the evening)

-   V3: remove pratesum features due to high missingness

-   V2: update context feature "type" with more information for values labeled other, expand mtry hyperparameter range downwards to include 10 and 15

# Presenting

April 2025:

-   Poster presented at Society of Biological Psychiatry

-   Poster presented at Collaborative Perspectives on Addiction

October 2024:

-   First Year Project Symposium

# Writing

October 2024:

-   First Year Project final paper to committee
