---
title: "Predictions"
---


```{r}
study <- params$study
cv <- params$cv
window <- params$window
model <- params$model
lead <- params$lead 
version <- params$version
```

Function conflicts
```{r, packages_workflow}
#| message: false
#| warning: false

# handle conflicts
options(conflicts.policy = "depends.ok")
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/fun_ml.R?raw=true")
tidymodels_conflictRules()
```

Packages for script
```{r, packages_script}
#| message: false
#| warning: false

library(tidyverse)
library(tidymodels)
library(tidyposterior)
# library(SHAPforxgboost)
# library(rstanarm)

theme_set(theme_classic()) 
```

Source support functions
```{r source_functions}
# EDA
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/fun_eda.R?raw=true")
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true")
# CHTC support functions
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/chtc/static_files/fun_chtc.R?raw=true")
```


Absolute paths
```{r, absolute_paths}
path_processed <- format_path(str_c("studydata/risk/data_processed/", study))
path_input <- format_path(str_c("studydata/risk/chtc/", study))
path_models <- format_path(str_c("studydata/risk/models/", study))
```


Chunk Defaults
```{r defaults}
#| include: false

knitr::opts_chunk$set(attr.output='style="max-height: 500px;"')

options(tibble.width = Inf)
options(tibble.print_max = Inf)
```


```{r}
metrics <- read_csv(here::here(path_models, str_c("inner_metrics_", version, "_", 
                                                    cv, "_", model, ".csv")))
```

## Get best config
```{r}
metrics_avg <- results_all %>% 
  group_by(algorithm, feature_set, hp1, hp2, hp3, resample) %>% 
   summarize(median_roc_auc = median(roc_auc),
             n_folds = n(), .groups = "drop") %>% 
  relocate(n_folds) %>% 
  arrange(desc(median_roc_auc)) |> 
  ungroup()

metrics_avg |> 
  slice(1:50) |> 
  print_kbl()

best_config <- metrics_avg |> 
  slice(1) |> 
  print()
```


## Get predictions for best configuration


Need to re-run same  nested CV but ONLY for this one configuration




