---
title: "Make Tables for GPS"
author: "Claire Punturieri"
date: "`r lubridate::today()`"
number-sections: true
output: 
  html_document:
    toc: true 
    toc_depth: 4
format:
  html:
    embed-resources: true
    toc: true
    toc-depth: 4
editor_options: 
  chunk_output_type: console
html-table-processing: none
---

```{r}
#| message: false
#| warning: false

library(tidyverse)
library(kableExtra, exclude = "group_rows")

source("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true")

path_shared <- format_path("risk/data_processed/shared")
```

## Demographics (table 1)

Load in study_dates.
```{r}
study_dates <- read_csv(file.path(path_shared,"study_dates_gps.csv"),
                        show_col_types = FALSE)
```

Pull list of subject IDs with at least one month data, credible lapse reporting, and sufficient GPS data.
```{r}
subids_dates <- study_dates |>  
  pull(subid) |>  
  unique()
```

Clean up file and filter down to only subjects used for GPS.
```{r}
dem_data <- read_csv(file.path(path_shared, "screen.csv"),
                     show_col_types = FALSE) |> 
  select(subid,  
         age = dem_1, 
         sex = dem_2, 
         race = dem_3, 
         hispanic = dem_4,
         education = dem_5,
         work = dem_6,
         income = dem_7,
         contains("dsm")) |> 
         mutate(hispanic = if_else(str_detect(hispanic, "Yes"), "1", "0")) |>  
    mutate(american_native = ifelse(str_detect(race,"American Indian/Alaska Native"),1,0),
        asian = ifelse(str_detect(race,"Asian"),1,0),
        pacific = ifelse(str_detect(race,"Native Hawaiian or Other Pacific Islander"),1,0),
        black = ifelse(str_detect(race,"Black/African American"),1,0),
        white = ifelse(str_detect(race,"White/Caucasian"),1,0),
        other = ifelse(str_detect(race,"Other/Multiracial"),1,0),
        ) |> 
  filter(subid %in% subids_dates)
```


Create table.
```{r}
#| label: tbl-1
#| tbl-cap: "Demographic Characteristics"

dem_data |>
  mutate(
    age_group = cut(
      age,
      breaks = c(18, 25, 35, 45, 55, 65, Inf),
      labels = c(
        "18-24",
        "25-34",
        "35-44",
        "45-54",
        "55-64",
        "65+"
      ),
      right = FALSE
    ),
    income_group = cut(
      income,
      breaks = c(0, 25000, 50000, 100000, 150000, Inf),
      labels = c(
        "<$25,000",
        "$25,000-$49,999",
        "$50,000-$99,999",
        "$100,000-$149,999",
        "≥$150,000"
      ),
    right = FALSE
  ),
  hispanic = if_else(hispanic == 1, "Yes", "No")) |>
  gtsummary::tbl_summary(include = c(age_group, sex,
                                     education, work,
                                     race, hispanic, income_group),
                         label = list(
                           age_group ~ "Age",
                           sex ~ "Sex At Birth",
                           race ~ "Race",
                           hispanic ~ "Ethnicity",
                           income_group ~ "Income"
                         )) |> 
  gtsummary::bold_labels()
```

## Fairness by auROC (table 2)

```{r}
contrast_dem_auroc <- read_csv((here::here(path_models, "pp_fairness_contrast_full.csv")))
```


```{r}
#| label: tbl-2
#| tbl-cap: "Bayesian comparisons of median auROCs by demographic subgroup"

contrast_dem_auroc |> 
  mutate(`Bayesian CI` = str_c("[", round(lower, 3), ", ", round(upper, 3), "]"),
         `Median auROC Difference` = as.character(round(median, 3)),
         Probability = sprintf("%.3f", probability)) |> 
  select(Contrast = contrast, `Median auROC Difference`, `Bayesian CI`, Probability) |> 
  knitr::kable() |> 
  kable_classic() |> 
  kableExtra::column_spec(1, width = "25em") |> 
  kableExtra::add_footnote(#label = footnote_table_model,
                           notation = "none",
                           escape = FALSE) 
```

## Fairness by LL (table 3)

```{r}
contrast_dem_ll <- read_csv((here::here(path_models, "pp_fairness_contrast_logloss.csv")))
```


```{r}
#| label: tbl-3
#| tbl-cap: "Bayesian comparisons of median mean Log Loss by demographic subgroup"

contrast_dem_ll |> 
  mutate(`Bayesian CI` = str_c("[", round(lower, 3), ", ", round(upper, 3), "]"),
         `Median mean Log Loss Difference` = as.character(round(median, 3)),
         Probability = sprintf("%.3f", probability)) |> 
  select(Contrast = contrast, `Median mean Log Loss Difference`, `Bayesian CI`, Probability) |> 
  knitr::kable() |> 
  kable_classic() |> 
  kableExtra::column_spec(1, width = "25em") |> 
  kableExtra::add_footnote(#label = footnote_table_model,
                           notation = "none",
                           escape = FALSE) 
```

## Bin counts for calibration plots (tables 4 + 5)


```{r}
probs <- read_csv(here::here(path_models, "outer_preds_v25_nested_2_x_5_6_x_5_full.csv"))

bin_width = 0.10
cal_raw <- probs |>
  mutate(
    prob = prob_raw,
    bins = cut(prob, breaks = seq(0, 1, bin_width)),
    lapse = if_else(label == "lapse", 1, 0),
    probs = "raw")
```

Table 4 - collapsed across folds.
```{r}
#| label: tbl-4
#| tbl-cap: "Bayesian comparisons of median mean Log Loss by demographic subgroup"

cal_raw |>
  group_by(bins, probs) |>
  summarise(
    mean_pred = mean(prob),
    mean_lapse = mean(lapse),
    n = n(),
    .groups = "drop"
  ) |>
  mutate(mean_pred = (round(mean_pred, digits = 3) * 100),
         mean_lapse = (round(mean_lapse, digits = 3)) * 100) |> 
  select(`Bin width` = bins, `Mean Probability of Lapse` = mean_pred,
         `Mean Lapse Percentage` = mean_lapse, Count = n) |>
  knitr::kable() |> 
  kable_classic() |> 
  kableExtra::column_spec(1, width = "25em") |> 
  kableExtra::add_footnote(#label = footnote_table_model,
                           notation = "none",
                           escape = FALSE) 
```


Table 5 - separated by fold.
```{r}
#| label: tbl-5
#| tbl-cap: "Bayesian comparisons of median mean Log Loss by demographic subgroup"

cal_raw |>
  group_by(bins, probs, outer_split_num) |>
  summarise(
    mean_pred = mean(prob),
    mean_lapse = mean(lapse),
    n = n(),
    .groups = "drop"
  ) |> 
  arrange(outer_split_num) |>
  mutate(mean_pred = (round(mean_pred, digits = 3) * 100),
         mean_lapse = (round(mean_lapse, digits = 3)) * 100) |> 
  select(`Bin width` = bins, `Fold` = outer_split_num,
         `Mean Probability of Lapse` = mean_pred,
         `Mean Lapse Percentage` = mean_lapse, Count = n) |>
  knitr::kable() |> 
  kable_classic() |> 
  kableExtra::column_spec(1, width = "25em") |> 
  kableExtra::add_footnote(#label = footnote_table_model,
                           notation = "none",
                           escape = FALSE) 
```

