---
title: "ana_bayes"
output: 
  html_document:
    toc: true 
    toc_depth: 4
format:
  html:
    embed-resources: true
params:
  version: "v25"
  cv: "nested_2_x_5_6_x_5"
  model: "full_v_baseline"
editor_options: 
  chunk_output_type: console
---

```{r}
#| message: false
#| warning: false

library(tidyverse)
library(tidymodels)
library(tidyposterior)

options(conflicts.policy = "depends.ok")
library(probably)

source("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true")

path_input <- format_path("risk/models/gps")

version <- params$version
cv <- params$cv
model <- params$model
```

```{r}
preds_full <- read_csv(here::here(path_input, str_c("outer_preds_", 
                                            version, "_", 
                                            cv, "_full.csv")))

preds_baseline <- read_csv(here::here(path_input, str_c("outer_preds_", 
                                            version, "_", 
                                            cv, "_baseline.csv")))
```

Create summary auroc by fold and repeat.
```{r}
auroc_full <- preds_full |>
  mutate(label = factor(label, levels = c("lapse", "no lapse"))) |>
  group_by(outer_split_num) |>
  roc_auc(truth = label, prob_raw) |>
  ungroup() |> 
  select(split_num = outer_split_num, "full" = .estimate) |> 
  arrange(split_num) |> 
  mutate(fold_num = rep(1:5, 6),
         repeat_num = c(rep(1, 5), rep(2, 5), rep(3, 5), 
                        rep(4, 5), rep(5, 5), rep(6, 5))) |> 
  select(-split_num) |> 
  relocate(full, .after = repeat_num)

auroc_baseline <- preds_baseline |>
  mutate(label = factor(label, levels = c("lapse", "no lapse"))) |>
  group_by(outer_split_num) |>
  roc_auc(truth = label, prob_raw) |>
  ungroup() |> 
  select(split_num = outer_split_num, "baseline" = .estimate) |> 
  arrange(split_num) |> 
  mutate(fold_num = rep(1:5, 6),
         repeat_num = c(rep(1, 5), rep(2, 5), rep(3, 5), 
                        rep(4, 5), rep(5, 5), rep(6, 5))) |> 
  select(-split_num) |> 
  relocate(baseline, .after = repeat_num)

auroc_all <- auroc_full |> 
  left_join(auroc_baseline, by = c("fold_num", "repeat_num"))
```

## Comparison: Full (demographics + GPS) vs Chance (.5)

> CP note: this model still has one divergent transition. Worth simplifying model structure? Discuss w john.

```{r}
# Repeated CV (id = repeat, id2 = fold within repeat)
# with a common variance:  statistic ~ model + (model | id/id2)
set.seed(101)
pp_full <- auroc_full |> 
  rename(id = repeat_num,
         id2 = fold_num) |> 
  perf_mod(formula = statistic ~ 1 + (1 | id/id2),
         transform = tidyposterior::logit_trans,  # for skewed & bounded AUC
         iter = 10000, chains = 4, adapt_delta = .9999, # still some divergence issues
         family = gaussian
)
```

Compare against chance performance.
```{r}
pp_full_tidy <- pp_full |> 
  tidy(seed = 123) 

q = c(.025, .5, .975)

pp_full_tidy |> 
  summarize(pp_median = quantile(posterior, probs = q[2]),
            pp_lower = quantile(posterior, probs = q[1]), 
            pp_upper = quantile(posterior, probs = q[3]))

pp_full_tidy |> 
 summarize(prob = mean(posterior > .5)) 
```

## Comparison: Full (demopgrahics + GPS) vs Baseline (demographics only)

```{r}
# Repeated CV (id = repeat, id2 = fold within repeat)
# with a common variance:  statistic ~ model + (model | id/id2)
set.seed(101)
pp_all <- auroc_all |> 
  rename(id = repeat_num,
         id2 = fold_num) |> 
  perf_mod(formula = statistic ~ model + (1 | id/id2),
         transform = tidyposterior::logit_trans,  # for skewed & bounded AUC
         iter = 8000, chains = 4, adapt_delta = .9995, # increased iteration from 2000 to fix divergence issues
         family = gaussian, 
)  

```

```{r}
pp_all_tidy <- pp_all |> 
  tidy(seed = 123) 

q = c(.025, .5, .975)
pp_all_tibble <- pp_all_tidy |> 
  group_by(model) |> 
  summarize(pp_median = quantile(posterior, probs = q[2]),
            pp_lower = quantile(posterior, probs = q[1]), 
            pp_upper = quantile(posterior, probs = q[3])) |> 
  mutate(model = factor(model, levels = c("baseline", "full"),
                        labels = c("baseline", "full"))) |> 
  arrange(model)

pp_all_tibble
```

## Write out files

```{r}
pp_full_tidy |> 
  write_csv(here::here(path_input, "posteriors_full.csv"))

pp_all_tidy |> 
  write_csv(here::here(path_input, "posteriors_all.csv"))

pp_all_tibble |> 
  write_csv(here::here(path_input, "pp_all_tibble.csv"))
```