---
title: "Model log loss and skill scores"
author: "Claire Punturieri"
date: "`r lubridate::today()`"
output: 
  html_document:
    toc: true 
    toc_depth: 4
format:
  html:
    embed-resources: true
params:
  version: "v25"
  cv: "nested_2_x_5_6_x_5"
  model: "full_v_baseline"
  batch: "full"
editor_options: 
  chunk_output_type: console
---

```{r}
#| message: false
#| warning: false

library(tidyverse)
library(tidymodels)

options(conflicts.policy = "depends.ok")
library(probably)

source("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true")

path_input <- format_path("risk/models/gps")

version <- params$version
cv <- params$cv
model <- params$model
batch <- params$batch
```

```{r}
preds <- read_csv(here::here(path_input, str_c("outer_preds_", 
                                            version, "_", 
                                            cv, "_", batch, ".csv")))
```

## Log loss

Plot histogram of 30 held out mean log loss.
```{r}
ll_summary <- preds |>
  mutate(label = factor(label, levels = c("lapse", "no lapse"))) |>
  group_by(outer_split_num) |>
  mn_log_loss(truth = label, prob_raw) |>
  ungroup()

ll_summary |>
  ggplot(aes(x = .estimate)) +
  geom_histogram(binwidth = .02, color = "white", fill = "#51856c") +
  theme_classic() +
  labs(x = "mean Log Loss",
       y = "Count")

median(ll_summary$.estimate)
```

## Skill scores

```{r}
skill_summary <- preds |>
  mutate(label = factor(label, levels = c("lapse", "no lapse"))) |>
  group_by(outer_split_num) |>
  summarize(p_null = unique(prev_inner), # lapse prevalence rate from training
            # ll of probs against outcomes
            ll_model = mn_log_loss_vec(label, prob_raw),
            # ll of same prob (prevalence) for everyone
            ll_null = mn_log_loss_vec(label, rep(p_null, n())),
            # look at difference in performance between
            # our model and one which only knows base rate
            skill = 1 - ll_model / ll_null,
            .groups = "drop")

skill_summary |>
  ggplot(aes(x = skill)) +
  geom_histogram(binwidth = .02) +
  geom_histogram(binwidth = .02, color = "white", fill = "#51856c") +
  theme_classic() +
  labs(x = "Skill Score (mean Log Loss)",
       y = "Count")

skill_summary |> pull(skill) |> mean()
skill_summary |> pull(skill) |> median()
```
